### ISSUE TITLE
setTimeout on wait method not waiting long enough for server to be ready

### ISSUE THREAD

**Issue by JustinBeaudry** [bevacqua/workshopper-wat#1]
https://github.com/bevacqua/perfschool/issues/4

A solution could be to set an env variable for that timeout, so maybe it could default to (as you mentioned: 10 seconds) but would defer to the environment if possible.

**Comment by bevacqua** [comment]
I think the best solution would be to `setInterval` waiting on figuring out whether a port is being used with [something like this](https://gist.github.com/timoxley/1689041), and then eventually timing out after something like 10s _(configurable)_ if we never find a listening app.

**Comment by JustinBeaudry** [comment]
#2 fixes this. Closing.
